### ISSUE TITLE
Grid has extra node at (0,0)

### ISSUE THREAD

**Issue by pmelchior** [pmelchior/skymapper#10]
![grid_problem](https://cloud.githubusercontent.com/assets/1463403/13975105/647cd7d2-f088-11e5-9b26-53322f708332.png)

There is an extra node at (RA, Dec) = (0,0) in what seems to be the axes patch. The other grid lines are OK. The example is simple:

```
import matplotlib.pyplot as plt
import numpy as np
import aea_projection
fig = plt.figure(figsize=(6, 4))

ra = np.random.uniform(size=1000, low=0, high=360)
dec = np.random.uniform(size=1000, low=-90, high=90)

ax = fig.add_subplot(111, aspect='equal', projection="aea", dec_1=-20., dec_2=30., ra_0=180, dec_0=0.)
ax.plot(ra, dec, '.')
ax.grid()
plt.show()
```

**Comment by rainwoodman** [comment]
This wouldn't have worked. there is an assertion that ra_0 must be enclosed by xlim and the default xlim is (0, 360)..

**Comment by pmelchior** [comment]
True. I've updated the script to reflect that `ra_0=180` in this example. I also lifted this requirement in d9fe32a402108f36934b001be49e245835d5a517 because it was not necessary and because it must be possible to have `ra_0=0`.

**Comment by rainwoodman** [comment]
This is probably fixed by #12?

Did I bring back the ra limits? Why must it be possible to have ra_0 = 0 on xlim of (0, 360) ?

**Comment by pmelchior** [comment]
I haven't seen the extra node in the latest commit.

ra_0 must be possible because you can have a situation where the data is centered on RA=0, and you don't want to break up the survey into a left and right patch.

**Comment by rainwoodman** [comment]
I think the current code is happy about symmetric over RA too -- if this is what you meant..

```
import matplotlib.pyplot as plt
import numpy as np
import aea_projection
reload(aea_projection)
fig = plt.figure(figsize=(6, 4))

ra = np.random.uniform(size=10000, low=-50, high=50)
dec = np.random.uniform(size=10000, low=-30, high=50)

ax = fig.add_subplot(111,  projection="aea")
ax.plot(ra[::100], dec[::100], 'x')
ax.histmap(ra, dec, nside=8)
ax.set_xlim(-50, 50)
#ax.set_center(0, None)
plt.show()
```
