### ISSUE TITLE
aea clipbox only works for ra_0 = 180

### ISSUE THREAD

**Issue by pmelchior** [pmelchior/skymapper#11]
![grid_problem2](https://cloud.githubusercontent.com/assets/1463403/13975229/8f561cce-f089-11e5-8fe0-e73c1b9bad01.png)

When using the example from #10 and using `ra_0=90`, the clipbox and the axis patch are shifted wrongly. Besides the graticule, also the mouse positions only work eastward of the RA=0 line and past the limit of RA that should be clipped.

This may be related to #10, but might also be a different problem.

**Comment by rainwoodman** [comment]
This is related to the wrapping in line 549. If I disable them at least the clip path is draw correctly. As of the misplaced grid points. I don't yet have a clue.

There may be some useful code to look up along these lines:

http://scitools.org.uk/cartopy/docs/latest/crs/projections.html

**Comment by pmelchior** [comment]
Yeah, they've apparently solved this issue, at least their examples look like it.
I had chosen to work with this package, but it's similarly bulky to install as Basemap was. However, if we insert the formulae of the map projections ourselves instead of calling external packages, we can still make use of their matplotlib axes here: https://github.com/SciTools/cartopy/tree/master/lib/cartopy/mpl

**Comment by rainwoodman** [comment]
It just seems to me they had to reimplement most methods of a matplotlib Axes, if not all?
