### ISSUE TITLE
Syntax error on import

### ISSUE THREAD

**Issue by xuod** [pmelchior/skymapper#23]
Hi,
I just installed skymapper using pip on OS X Mojave with Python 2.7 from HomeBrew and have an error on import:
```
In [1]: import skymapper as skm
  File "/usr/local/lib/python2.7/site-packages/skymapper/survey/__init__.py", line 22
    class Survey(BaseSurvey, metaclass=Meta):
                                      ^
SyntaxError: invalid syntax
```
Didn't find any simple fix, but it seems to be related to the use of metaclass. When I reuse the import command right after, I get a different error: 
```
In [2]: import skymapper as skm
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-b7fd60c3368c> in <module>()
----> 1 import skymapper as skm

/usr/local/lib/python2.7/site-packages/skymapper/__init__.py in <module>()
      8     survey_register[cls.__name__] = cls
      9
---> 10 from . import survey
     11 from .map import *
     12 from .projection import *

ImportError: cannot import name survey
```
Any idea?
Thanks for helping!

**Comment by pmelchior** [comment]
I can confirm it. It's a python2.7 problem with the metaclass structure. I'll have to see how to avoid it.

**Comment by pmelchior** [comment]
Cyrille, can you test the latest `master`, where I have fixed the import? I couldn't fully test it because I have no python2.7 with matplotlib right now. If you confirm it's working, I'll roll it out to pypi.

**Comment by xuod** [comment]
Hi Peter, the import works fine with the latest commit!

However the example script seems broken (pretty sure this is not related because I hadn't tried it):
```
Traceback (most recent call last):
  File "example1.py", line 53, in <module>
    ra, dec = getCatalog(size, surveyname="DES")
  File "example1.py", line 28, in getCatalog
    ra_fp, dec_fp = skm.survey_register[surveyname].getFootprint()
TypeError: unbound method getFootprint() must be called with DES instance as first argument (got nothing instead)
```

**Comment by pmelchior** [comment]
OK, one problem down...

It seems that the survey specs have not registered. Can you paste here the contents of `skm.survey_register`, please.

**Comment by pmelchior** [comment]
I found the bug. Please confirm it's working now.

**Comment by xuod** [comment]
`skm.survey_register` is `{'DES': skymapper.survey.DES, 'Survey': skymapper.survey.Survey}`. And I've got another bug:
```
Traceback (most recent call last):
  File "example1.py", line 58, in <module>
    proj = skm.Albers.optimize(ra, dec, reduce_fct=crit)
TypeError: optimize() got an unexpected keyword argument 'reduce_fct'
```

**Comment by pmelchior** [comment]
Outdated example... Try again

**Comment by xuod** [comment]
Works great! Thanks!

**Comment by pmelchior** [comment]
Good. Thanks for testing. I'll put the updated version to pypi now.
